### PR TITLE
Integrate with OVS 2.9 for no-hyperv support

### PR DESCRIPTION
**Pull request by rajatchopra**
@glennswest PTAL

@aserdean Please review

This will still expect OVS 2.9 to be downloaded and pre-installed on the Windows machine.

### CODE REVIEW

**Comment by cooktheryan** [comment]
:+1:

**Comment by glennswest** [comment]
1. Needs to be in 3.11 folder - glennswest/openshift-windows is upstream please
2. Hardcoding the nic even using a parameter file is a bit of a regression, i'd prefer it to use the auto-detect logic.
3. only supported in 3.11 - Not going back to 3.9 or 3.10

**Comment by rajatchopra** [comment]
>     1. Needs to be in 3.11 folder - glennswest/openshift-windows is upstream please
> 
>     2. Hardcoding the nic even using a parameter file is a bit of a regression, i'd prefer it to use the auto-detect logic.
> 
>     3. only supported in 3.11 - Not going back to 3.9 or 3.10

Ack on 3.11, agreed it should not be ported back.
On the nic name, I agree with you, I wanted to try this out first and then figure out a way of auto-detect or something.

Rebasing in a few..

**Comment by aserdean** [comment]
@rajatchopra , @glennswest I think this PR is obsolete and can be closed, since it already been dealt with in: https://github.com/openshift/openshift-windows/commit/4a1ce26440e40e8dec7578bae663f186a8d2a770

**Pull request closed without merging**
